const skillNames = [
  'Java',
  'C++',
  'Python',
  'JavaScript',
  'Ruby',
  'PHP',
  'Swift',
  'Kotlin',
  'TypeScript',
  'HTML',
  'CSS',
  'UX Design',
  'UI Design',
  'Data Structures',
  'Algorithms',
  'Machine Learning',
  'Web Development',
  'Mobile Development',
  'Cloud Computing',
  'DevOps',
  'Project Management',
  'Agile Methodologies',
  'Database Management',
  'SQL',
  'Software Testing',
  'Cybersecurity',
  'Network Administration',
  'Blockchain',
  'Docker',
  'REST API Design',
];

export default skillNames;
